services:
  - type: web
    name: control-gastos-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/index.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://gastos_db_mfgc_user:R8CkcsqvDhs9cHMZoyjRHw1pjZgPaBrd@dpg-d0kab556ubrc73b4e0p0-a.oregon-postgres.render.com/gastos_db_mfgc
    autoDeploy: true
    rootDir: backend
